- id: '1577787182078'
  alias: Woonkamer - Verlichting - Lux - Aan
  description: ''
  trigger:
  - above: 3
    below: 12
    device_id: 3301c784485e43ca92a8576aae1d14c6
    domain: sensor
    entity_id: sensor.woonkamer_light_level
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: illuminance
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: state
      entity_id: light.keuken
      state: 'off'
  action:
  - data:
      group_name: Beneden
      scene_name: BenedenDimmed
    service: hue.hue_activate_scene
  - data:
      group_name: Woonkamer
      scene_name: WoonkamerDimmed
    service: hue.hue_activate_scene
  - data:
      group_name: Keuken
      scene_name: KeukenDimmed
    service: hue.hue_activate_scene
- id: '1577787317842'
  alias: Woonkamer - Verlichting - Lux - Uit
  description: ''
  trigger:
  - above: 15
    device_id: 3301c784485e43ca92a8576aae1d14c6
    domain: sensor
    entity_id: sensor.woonkamer_light_level
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: illuminance
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: light.keuken
      state: 'on'
  action:
  - data: {}
    entity_id: light.beneden
    service: light.turn_off
  - entity_id: light.keuken
    service: light.turn_off
  - data: {}
    entity_id: light.woonkamer
    service: light.turn_off
- id: '1577796092710'
  alias: Hal - Verlichting - Motion - Dag
  description: ''
  trigger:
  - device_id: 90706093c60c4af29471cd60bbdd2b41
    domain: binary_sensor
    entity_id: binary_sensor.hal_motion
    platform: device
    type: motion
  condition:
  - after: 08:00
    before: '20:00'
    condition: time
  action:
  - data:
      group_name: Hal & Overlopen
      scene_name: Dimmed
    service: hue.hue_activate_scene
- id: '1577796092709'
  alias: Hal - Verlichting - Motion - Nacht
  description: ''
  trigger:
  - device_id: 90706093c60c4af29471cd60bbdd2b41
    domain: binary_sensor
    entity_id: binary_sensor.hal_motion
    platform: device
    type: motion
  condition:
  - after: '20:00'
    before: '23:59'
    condition: time
  action:
  - data:
      group_name: Hal & Overlopen
      scene_name: Nightlight
    service: hue.hue_activate_scene
- id: '1577871936187'
  alias: Slaapkamer Lex en Boris - Verlichting - Aan
  description: ''
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - entity_id: light.slaapkamer_lex
    service: light.turn_on
  - entity_id: light.slaapkamer_boris
    service: light.turn_on
- id: '1577872674979'
  alias: Slaapkamer Lex en Boris - Verlichting - Uit
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition: []
  action:
  - entity_id: light.slaapkamer_lex
    service: light.turn_off
  - entity_id: light.slaapkamer_boris
    service: light.turn_off
- id: '1577872674980'
  alias: Verlichting - Verzend notificatie
  trigger:
  - platform: state
    entity_id: media_player.livingroom_tv_2
    to: 'off'
    for: 0:02:00
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
  action:
  - service: notify.family
    data:
      message: De verlichting staat nog aan!
      data:
        push:
          badge: 0
          category: lampen
  mode: single
- id: '1577872674981'
  alias: Verlichting - Notificatie actie
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LAMPEN_UIT
  action:
  - data: {}
    entity_id: light.woonkamer
    service: light.turn_off
  - entity_id: light.keuken
    service: light.turn_off
  - entity_id: light.buiten
    service: light.turn_off
- id: '1577872674982'
  alias: Vakantie - Apparatuur uitschakelen
  trigger:
  - entity_id: input_boolean.vakantie
    from: 'off'
    platform: state
    to: 'on'
  action:
  - entity_id: light.woonkamer_tv
    service: light.turn_off
  - entity_id: light.slaapkamer_tv
    service: light.turn_off
  - entity_id: switch.wasmachine
    service: switch.turn_off
  - entity_id: switch.droger
    service: switch.turn_off
  - data: {}
    entity_id: light.woonkamer_tv
    service: light.turn_off
- id: '1577872674983'
  alias: Vakantie - Apparatuur inschakelen
  trigger:
  - entity_id: input_boolean.vakantie
    from: 'on'
    platform: state
    to: 'off'
  action:
  - entity_id: light.woonkamer_tv
    service: light.turn_on
  - entity_id: switch.wasmachine
    service: switch.turn_on
  - entity_id: switch.droger
    service: switch.turn_on
- id: '1578407345450'
  alias: Hal - Verlichting - Motion - Uit
  description: ''
  trigger:
  - device_id: 90706093c60c4af29471cd60bbdd2b41
    domain: binary_sensor
    entity_id: binary_sensor.hal_motion
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - entity_id: light.hal_overlopen
    service: light.turn_off
- id: '1581204986110'
  alias: Buiten - Verlichting - Aan
  description: ''
  trigger:
  - type: illuminance
    platform: device
    device_id: 3564efe7aedf4465a41cf9f88d14c156
    entity_id: sensor.buiten_sensor_light_level
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 0
      seconds: 30
    above: 2
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.buiten
      state: 'off'
  - condition: time
    after: '16:00:00'
    before: 00:00:00
  action:
  - data:
      group_name: Buiten
      scene_name: Bright
    service: hue.hue_activate_scene
  mode: single
- id: '1581205043194'
  alias: Buiten - Verlichting - Uit
  description: ''
  trigger:
  - at: 00:00
    platform: time
  condition:
  - condition: state
    entity_id: light.buiten
    state: 'on'
  action:
  - entity_id: light.buiten
    service: light.turn_off
- id: '1590339256250'
  alias: Buiten - Verlichting - Motion
  description: ''
  trigger:
  - device_id: 3564efe7aedf4465a41cf9f88d14c156
    domain: binary_sensor
    entity_id: binary_sensor.buiten_sensor_motion
    platform: device
    type: motion
  condition:
  - after: 01:00
    before: 06:00
    condition: time
  action:
  - data:
      message: Er is beweging bij de voordeur gedecteerd!
      title: Beweging!
    service: notify.family
  - brightness_pct: 100
    device_id: 4610da9448cc49f497dd9eaa8f0f2e45
    domain: light
    entity_id: light.buiten_voordeur
    type: turn_on
  - brightness_pct: 100
    device_id: 909c13edc42142178ee0988238b9734d
    domain: light
    entity_id: light.buiten_garage
    type: turn_on
  - type: turn_on
    device_id: 98244d710640498d8a48419a483ff435
    entity_id: switch.apple_tv
    domain: switch
  - delay: 00:7:30
  - device_id: 4610da9448cc49f497dd9eaa8f0f2e45
    domain: light
    entity_id: light.buiten_voordeur
    type: turn_off
  - device_id: 909c13edc42142178ee0988238b9734d
    domain: light
    entity_id: light.buiten_garage
    type: turn_off
  - type: turn_off
    device_id: 98244d710640498d8a48419a483ff435
    entity_id: switch.apple_tv
    domain: switch
  mode: single
- id: '1597609986589'
  alias: Kinderen - Wakker - Verzend notificatie
  description: ''
  trigger:
  - device_id: 3301c784485e43ca92a8576aae1d14c6
    domain: binary_sensor
    entity_id: binary_sensor.woonkamer_motion
    platform: device
    type: motion
  condition:
  - after: 05:00
    before: 08:00
    condition: time
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.kinderen_wakker_verzend_notificatie.attributes.last_triggered
      | default(0)) | int > 10800)}}'
  action:
  - data:
      title: De kinderen zijn beneden!
      message: Stelletje boeven!
    service: notify.family
  - service: hue.hue_activate_scene
    data:
      group_name: Beneden
      scene_name: BenedenDimmed
  - service: hue.hue_activate_scene
    data:
      group_name: Woonkamer
      scene_name: WoonkamerDimmed
  - service: hue.hue_activate_scene
    data:
      group_name: Keuken
      scene_name: KeukenDimmed
  - service: hue.hue_activate_scene
    data:
      group_name: Hal & Overlopen
      scene_name: Dimmed
  mode: single
- id: '1600694311899'
  alias: Home Assistant - Set Theme on Startup
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: ios-dark-mode-blue-red-alternative
  mode: single
- id: '1600928113047'
  alias: Buiten - Temperatuur - Vorst
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.buiten_sensor_temperature
    below: '0'
    for: '10'
  condition:
  - condition: time
    after: 07:00
    before: 07:15
  - condition: template
    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.buiten_temperatuur_vorst.attributes.last_triggered
      | default(0)) | int > 10800)}}'
  action:
  - service: notify.family
    data:
      title: Het vriest vandaag!
      message: Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. De buitentemperatuur
        is {{ states.sensor.buiten_sensor_temperature.state }} graden!
  mode: single
- id: '1601844634937'
  alias: BMW - Update every 5 minutes
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: bmw_connected_drive.update_state
    data: {}
  mode: single
- id: '1601844868829'
  alias: BMW - Unlock - Verzend notificatie
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.640i_xdrive_door_lock_state
    from: Locked
    to: Unlocked
  condition:
  - condition: time
    after: 00:00
    before: 05:30
  action:
  - service: notify.mobile_app_skynet_mobile
    data:
      message: De auto is open!
      title: BMW geopend!
  - service: tts.google_say
    data:
      entity_id: media_player.other_speaker
      message: De auto is open!
  - service: hue.hue_activate_scene
    data:
      group_name: Buiten
      scene_name: Bright
  - service: hue.hue_activate_scene
    data:
      group_name: Beneden
      scene_name: Bright
  - delay: 00:10:00
  - service: light.turn_off
    data: {}
    entity_id: light.beneden
  - service: light.turn_off
    data: {}
    entity_id: light.buiten
  mode: single
- id: '1601849976543'
  alias: Buiten - Volle maan - Verzend notificatie
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.moon
    to: full_moon
  condition: []
  action:
  - service: notify.mobile_app_skynet_mobile
    data:
      title: Full moon!
      message: Full moon!
  mode: single
