# - id: '1635878969253'
#   alias: Test
#   description: Test
#   use_blueprint:
#     path: homeassistant/motion_light.yaml
#     input:
#       motion_entity: binary_sensor.hue_outdoor_motion_sensor_1_motion
#       no_motion_wait: 299
#       light_target:
#         entity_id:
#         - light.beneden
#         - light.buitenvoor
- id: "1635879140349"
  alias: New Automation
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.vakantie
      from: "off"
      to: "on"
  condition: []
  action:
    - service: climate.turn_off
      target:
        entity_id: climate.woonkamer
  mode: single
