- id: '1644654884689'
  alias: Badkamer - Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_motion
    to: 'on'
  condition: []
  action:
  - service: fan.set_speed
    data:
      speed: high
    target:
      entity_id: fan.buva_fan
  mode: single
- id: '1644655000205'
  alias: Badkamer
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.badkamer_motion
    to: 'on'
  condition: []
  action:
  - service: fan.set_speed
    data:
      speed: high
    target:
      entity_id: fan.buva_fan
  mode: single
