- platform: template
  sensors:
    oppas:
      friendly_name: Oppas
      value_template: '{{ states.input_boolean.oppas.state == "on" }}'
      device_class: presence

- platform: ping
  host: !secret lgwebostv_host_1
  name: TV Ping Woonkamer
  scan_interval: 10
  count: 5

- platform: ping
  host: !secret lgwebostv_host_2
  name: TV Ping Slaapkamer
  scan_interval: 10
  count: 5