homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    language: 'nl'
    service_name: google_say
    base_url: !secret http_url

updater:
  include_used_components: true

proximity:

recorder:
  purge_keep_days: 7
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date

logger:
  default: info
  logs:
    custom_components.sensor.afvalwijzer: debug
    custom_components.afvalwijzer: debug

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend: !include frontend.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml

ios:
  push:
    categories:
      - name: Afval
        identifier: 'afval'
        actions:
          - identifier: 'MARK_TRASH_MOVED'
            title: 'Afval verwerkt'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: Lampen
        identifier: 'lampen'
        actions:
          - identifier: 'LAMPEN_UIT'
            title: 'Lampen uit'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'

notify:
  - platform: group
    name: family
    services:
      - service: mobile_app_brams_iphone
      - service: mobile_app_lieke_iphone
  - platform: group
    name: bram
    services:
      - service: mobile_app_brams_iphone

timer:
  hal_overlopen:
    duration: '00:5:00'

hue:
  bridges:
    - host: !secret philips_hue_host
      allow_unreachable: true
      allow_hue_groups: true

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

media_player:
  - platform: androidtv
    name: NVidia Shield
    host: !secret nvidia_shield

webostv:
  - host: !secret lgwebostv_host_1
    name: Livingroom TV
  - host: !secret lgwebostv_host_2
    name: Bedroom TV

cast:
  media_player:
  - host: !secret nvidia_shield
  - host: !secret lgwebostv_host_1
  - host: !secret lgwebostv_host_2

device_tracker:
#  - platform: google_maps
#    username: !secret lieke_gmail 
#    max_gps_accuracy: 200
  - platform: nmap_tracker
    home_interval: 120
    hosts:
      - !secret nmap_hosts
