homeassistant:
  packages: !include_dir_named packages

default_config:

recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

tts:
  - platform: google_translate
    language: "nl"
    service_name: google_say
    base_url: !secret http_url
    # cache: true
    # cache_dir: /tmp/tts
    # time_memory: 300

updater:
  include_used_components: true

proximity:

logger:
  default: info
  logs:
    custom_components.afvalwijzer: debug
    #homeassistant.components.scrape: debug

lovelace:
  resources:
    - url: /local/multiple-entity-row.js?v=4.1.1
      type: module

#influxdb:
#  host: 192.168.1.15
#  max_retries: 3
#  default_measurement: state
#  include:
#    entities:
#      - light.woonkamer
#      - light.hal_overlopen
#      - sensor.hal_light_level
#      - sensor.woonkamer_light_level
#      - media_player.livingroom_tv
#      - media_player.bedroom_tv
#      - sensor.wasmachine_watts
#      - sensor.droger_watts
#      - sensor.living_room_thermostat_humidity
#      - sensor.living_room_thermostat_temperature
#      - sensor.living_room_thermostat_target
#      - weather.home

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_number: !include input_numbers.yaml
input_boolean: !include input_booleans.yaml
#frontend: !include frontend.yaml
frontend:
  themes: !include_dir_merge_named themes

#mobile_app:

ios:
  push:
    categories:
      - name: Afval
        identifier: "afval"
        actions:
          - identifier: "MARK_WASTE_MOVED"
            title: "Afval verwerkt"
            activationMode: "background"
            authenticationRequired: no
            destructive: yes
            behavior: "default"
      - name: Lampen
        identifier: "lampen"
        actions:
          - identifier: "LAMPEN_UIT"
            title: "Lampen uit"
            activationMode: "background"
            authenticationRequired: no
            destructive: yes
            behavior: "default"
          - identifier: "DISMISS"
            title: "Dismiss"
            activationMode: "background"
            authenticationRequired: no
            destructive: no
            behavior: "default"

notify:
  - platform: group
    name: family
    services:
      - service: mobile_app_skynet_mobile
      - service: mobile_app_lieke_iphone
  - platform: group
    name: bram
    services:
      - service: mobile_app_skynet_mobile

timer:
  hal_overlopen:
    duration: "00:5:00"

bmw_connected_drive:
  bmw_640i_xdrive:
    username: !secret bmw_username
    password: !secret bmw_password
    region: rest_of_world
    read_only: true

webostv:
  - host: !secret lgwebostv_host_1
    name: Livingroom TV
  - host: !secret lgwebostv_host_2
    name: Bedroom TV
#device_tracker:
# - platform: google_maps
#   username: !secret lieke_gmail
#   max_gps_accuracy: 200
# - platform: nmap_tracker
#   home_interval: 120
#   hosts:
#     - !secret nmap_hosts
