- platform: season
  type: astronomical
- platform: moon
- platform: uptime
- platform: time_date

- platform: version
  name: 'HASS - Version installed'
  source: local

- platform: version
  name: 'HASS - Version available'
  beta: false
  image: default
  source: docker

- platform: template
  sensors:
    time_of_day:
      friendly_name: 'Time of Day'
      entity_id: sensor.time_date
      value_template: >-
        {% if   now().strftime("%H:%M") < "08:00" %} night
        {% elif now().strftime("%H:%M") < "18:00" %} daytime
        {% elif now().strftime("%H:%M") < "24:00" %} evening
        {% endif %}
    day_of_year:
      friendly_name: 'Day Number'
      entity_id: sensor.time_date
      value_template: '{{ now().strftime("%j") }}'
    week_of_year:
      friendly_name: 'Week Number'
      entity_id: sensor.time_date
      value_template: '{{ now().strftime("%U") }}'

- platform: template
  sensors:
    woonkamer_light_level_lux:
      friendly_name: 'Woonkamer Light Level - LUX'
      value_template: '{{ states.sensor.woonkamer_light_level.attributes.lightlevel }}'
      unit_of_measurement: lux
    hal_light_level_lux:
      friendly_name: 'Hal Light Level - LUX'
      value_template: '{{ states.sensor.hal_light_level.attributes.lightlevel }}'
      unit_of_measurement: lux

- platform: syncthru
  resource: !secret printer
  name: Samsung Printer

- platform: synologydsm
  host: !secret nas_host_ip
  port: 5000
  ssl: 'false'
  username: !secret nas_username
  password: !secret nas_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - disk_smart_status
    - disk_temp
    - volume_percentage_used
    - volume_size_total

- platform: dnsip
  name: IP adres