################################################
## Packages
################################################
homeassistant:

################################################
## Automation
################################################
automation:
  - id: "1590339256250"
    alias: Buiten - Verlichting - Motion
    trigger:
      - device_id: 3564efe7aedf4465a41cf9f88d14c156
        domain: binary_sensor
        entity_id: binary_sensor.buiten_sensor_motion
        platform: device
        type: motion
    condition:
      - condition: and
        conditions:
          - after: "01:00:00"
            before: "06:00:00"
            condition: time
          - condition: state
            entity_id: input_boolean.vakantie
            state: "off"
    action:
      - data:
          message: Er is beweging bij de voordeur gedecteerd!
          title: Beweging!
        service: notify.family
      - service: light.turn_on
        target:
          entity_id: light.buiten_voordeur
        data:
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: light.buiten_garage
        data:
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: light.studeerkamer_links
        data:
          brightness_pct: 100
      - service: light.turn_on
        target:
          entity_id: light.studeerkamer_rechts
        data:
          brightness_pct: 100

      # - delay: 00:10:00
  - id: "1578407345450"
    alias: Buiten - Verlichting - Motion - Uit
    trigger:
      - device_id: 3564efe7aedf4465a41cf9f88d14c156
        domain: binary_sensor
        entity_id: binary_sensor.buiten_sensor_motion
        for:
          hours: 0
          minutes: 10
          seconds: 0
        platform: device
        type: no_motion
    condition:
      - condition: and
        conditions:
          - after: "01:00:00"
            before: "06:00:00"
            condition: time
          - condition: state
            entity_id: input_boolean.vakantie
            state: "off"
    action:
      - entity_id: light.buiten_voordeur
        service: light.turn_off
      - entity_id: light.buiten_garage
        service: light.turn_off
      - entity_id: light.studeerkamer_links
        service: light.turn_off
      - entity_id: light.studeerkamer_rechts
        service: light.turn_off

  - id: "1597609986589"
    alias: Kinderen - Wakker - Verzend notificatie
    trigger:
      - device_id: 3301c784485e43ca92a8576aae1d14c6
        domain: binary_sensor
        entity_id: binary_sensor.woonkamer_motion
        platform: device
        type: motion
    condition:
      - after: "05:00:00"
        before: "08:00:00"
        condition: time
      - condition: template
        value_template:
          "{{ (as_timestamp(now()) - as_timestamp(states.automation.kinderen_wakker_verzend_notificatie.attributes.last_triggered
          | default(0)) | int > 10800)}}"
    action:
      - data_template:
          title: "Woonkamer:"
          message: 'Er is beweging - Tijdstip: {{now().strftime("%H:%M")}}'
        service: notify.family
      - service: scene.turn_on
        target:
          entity_id: scene.woonkamer_woonkamerdimmed
      - service: scene.turn_on
        target:
          entity_id: scene.keuken_keukendimmed
      - service: scene.turn_on
        target:
          entity_id: scene.hal_overlopen_dimmed

  - id: "1601844634937"
    alias: BMW - Update every 5 minutes
    trigger:
      - platform: time_pattern
        minutes: /5
    condition: []
    action:
      - service: bmw_connected_drive.update_state

  - id: "1601844868829"
    alias: BMW - Unlock - Verzend notificatie
    trigger:
      - platform: state
        entity_id: binary_sensor.640i_xdrive_door_lock_state
        from: Locked
        to: Unlocked
    condition:
      - condition: time
        after: "00:00:00"
        before: "05:30:00"
    action:
      - service: notify.bram
        data:
          message: De auto is open!
          title: BMW geopend!
      - service: tts.google_say
        data:
          entity_id: media_player.other_speaker
          message: De auto is open!
      - service: scene.turn_on
        target:
          entity_id: scene.buiten_bright
      - service: scene.turn_on
        target:
          entity_id: scene.woonkamer_bright
      - service: scene.turn_on
        target:
          entity_id: scene.keuken_bright
      - service: scene.turn_on
        target:
          entity_id: scene.hal_overlopen_bright
      - delay: 00:10:00
      - entity_id: light.woonkamer
        service: light.turn_off
      - entity_id: light.keuken
        service: light.turn_off
      - entity_id: light.buiten
        service: light.turn_off
      - entity_id: light.hal_overlopen
        service: light.turn_of

  - id: "1600928113047"
    alias: Buiten - Temperatuur - Vorst
    trigger:
      - platform: numeric_state
        entity_id: sensor.buiten_sensor_temperature
        below: "0"
        for: "00:10:00"
    condition:
      - condition: time
        after: "06:00:00"
        before: "08:00:00"
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(states.automation.buiten_temperatuur_vorst.attributes.last_triggered| default(0)) | int > 10800)}}"
    action:
      - service: notify.family
        data:
          title: Het vriest vandaag!
          message: >
            Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. De buitentemperatuur
            is {{ states.sensor.buiten_sensor_temperature.state }} graden!
