################################################
## Packages
################################################
homeassistant:

################################################
## Automation
################################################
automation:
  - id: "1590339256250"
    alias: Buiten - Verlichting - Motion
    trigger:
      - device_id: 3564efe7aedf4465a41cf9f88d14c156
        domain: binary_sensor
        entity_id: binary_sensor.buiten_sensor_motion
        platform: device
        type: motion
    condition:
      - after: "01:00:00"
        before: "06:00:00"
        condition: time
    action:
      - data:
          message: Er is beweging bij de voordeur gedecteerd!
          title: Beweging!
        service: notify.family
      - brightness_pct: 100
        device_id: 4610da9448cc49f497dd9eaa8f0f2e45
        domain: light
        entity_id: light.buiten_voordeur
        type: turn_on
      - brightness_pct: 100
        device_id: 909c13edc42142178ee0988238b9734d
        domain: light
        entity_id: light.buiten_garage
        type: turn_on
      - type: turn_on
        device_id: 98244d710640498d8a48419a483ff435
        entity_id: switch.apple_tv
        domain: switch
      - delay: 00:7:30
      - device_id: 4610da9448cc49f497dd9eaa8f0f2e45
        domain: light
        entity_id: light.buiten_voordeur
        type: turn_off
      - device_id: 909c13edc42142178ee0988238b9734d
        domain: light
        entity_id: light.buiten_garage
        type: turn_off
      - type: turn_off
        device_id: 98244d710640498d8a48419a483ff435
        entity_id: switch.apple_tv
        domain: switch

  - id: "1597609986589"
    alias: Kinderen - Wakker - Verzend notificatie
    trigger:
      - device_id: 3301c784485e43ca92a8576aae1d14c6
        domain: binary_sensor
        entity_id: binary_sensor.woonkamer_motion
        platform: device
        type: motion
    condition:
      - after: "05:00:00"
        before: "08:00:00"
        condition: time
      - condition: template
        value_template:
          "{{ (as_timestamp(now()) - as_timestamp(states.automation.kinderen_wakker_verzend_notificatie.attributes.last_triggered
          | default(0)) | int > 10800)}}"
    action:
      - data_template:
          title: "Woonkamer:"
          message: 'Er is beweging - Tijdstip: {{now().strftime("%H:%M")}}'
        service: notify.family
      - service: hue.hue_activate_scene
        data:
          scene_name: BenedenDimmed
          group_name: Beneden
      - service: hue.hue_activate_scene
        data:
          group_name: Woonkamer
          scene_name: WoonkamerDimmed
      - service: hue.hue_activate_scene
        data:
          group_name: Keuken
          scene_name: KeukenDimmed
      - service: hue.hue_activate_scene
        data:
          group_name: Hal & Overlopen
          scene_name: Dimmed

  - id: "1601844634937"
    alias: BMW - Update every 5 minutes
    trigger:
      - platform: time_pattern
        minutes: /5
    condition: []
    action:
      - service: bmw_connected_drive.update_state

  - id: "1601844868829"
    alias: BMW - Unlock - Verzend notificatie
    trigger:
      - platform: state
        entity_id: binary_sensor.640i_xdrive_door_lock_state
        from: Locked
        to: Unlocked
    condition:
      - condition: time
        after: "00:00:00"
        before: "05:30:00"
    action:
      - service: notify.mobile_app_skynet_bram
        data:
          message: De auto is open!
          title: BMW geopend!
      - service: tts.google_say
        data:
          entity_id: media_player.other_speaker
          message: De auto is open!
      - service: hue.hue_activate_scene
        data:
          group_name: Buiten
          scene_name: Bright
      - service: hue.hue_activate_scene
        data:
          group_name: Beneden
          scene_name: Bright
      - delay: 00:10:00
      - service: light.turn_off
        entity_id: light.beneden
      - service: light.turn_off
        entity_id: light.buiten

  - id: "1600928113047"
    alias: Buiten - Temperatuur - Vorst
    trigger:
      - platform: numeric_state
        entity_id: sensor.buiten_sensor_temperature
        below: "0"
        for: "00:10:00"
    condition:
      - condition: time
        after: "07:00:00"
        before: "07:15:00"
      - condition: template
        value_template:
          "{{ (as_timestamp(now()) - as_timestamp(states.automation.buiten_temperatuur_vorst.attributes.last_triggered
          | default(0)) | int > 10800)}}"
    action:
      - service: notify.family
        data:
          title: Het vriest vandaag!
          message:
            Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. De buitentemperatuur
            is {{ states.sensor.buiten_sensor_temperature.state }} graden!
