################################################
## Packages / Dsmr
################################################
homeassistant:
  customize:
    sensor.dsmr_electricity:
      friendly_name: Electricity Today
      icon: mdi:power-plug
    sensor.dsmr_gas:
      friendly_name: Gas Today
      icon: mdi:power-plug

################################################
## Sensor
################################################
sensor:
  - platform: rest
    name: dsmr_electricity
    resource: !secret dsmr_today
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.electricity1 | round(2) }}"
    headers:
      X-AUTHKEY: !secret dsmr_token

  - platform: rest
    name: dsmr_gas
    resource: !secret dsmr_today
    unit_of_measurement: "m³"
    value_template: "{{ value_json.gas | round(2) }}"
    headers:
      X-AUTHKEY: !secret dsmr_token
