################################################
## Packages / Power Plugs
################################################
homeassistant:
  customize:
    switch.wasmachine:
      friendly_name: Wasmachine
    switch.droger:
      friendly_name: Droger
    sensor.wasmachine_watts:
      friendly_name: Huidig verbruik wasmachine
      icon: mdi:washing-machine
    sensor.droger_watts:
      friendly_name: Huidig verbruik droger
      icon: mdi:tumble-dryer
    sensor.wasmachine_status_time:
      friendly_name: Wasmachine draaitijd
      icon: mdi:washing-machine
    sensor.wasmachine_status_value:
      friendly_name: Wasmachine status
      icon: mdi:washing-machine
    sensor.droger_status_time:
      friendly_name: Droger draaitijd
      icon: mdi:tumble-dryer
    sensor.droger_status_value:
      friendly_name: Droger status
      icon: mdi:tumble-dryer

################################################
## Inputs
################################################
input_boolean:
  wasmachine:
    name: Wasmachine status
    initial: off
    icon: mdi:washing-machine
  droger:
    name: Droger status
    initial: off
    icon: mdi:tumble-dryer

input_number:
  wasmachine_start:
    name: Wasmachine start
    min: 0
    max: 999999999
  wasmachine_stop:
    name: Wasmachine stop
    min: 0
    max: 999999999
  droger_start:
    name: Droger start
    min: 0
    max: 999999999
  droger_stop:
    name: Droger stop
    min: 0
    max: 999999999

################################################
## Sensor
################################################
sensor:
# WASMACHINE
  - platform: template
    sensors:
      wasmachine_amps:
        friendly_name_template: "{{ states.switch.wasmachine.name}} Current"
        value_template: '{{ states.switch.wasmachine.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      wasmachine_watts:
        friendly_name_template: "{{ states.switch.wasmachine.name}} Current Consumption"
        value_template: '{{ states.switch.wasmachine.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      wasmachine_total_kwh:
        friendly_name_template: "{{ states.switch.wasmachine.name}} Total Consumption"
        value_template: '{{ states.switch.wasmachine.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      wasmachine_volts:
        friendly_name_template: "{{ states.switch.wasmachine.name}} Voltage"
        value_template: '{{ states.switch.wasmachine.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      wasmachine_today_kwh:
        friendly_name_template: "{{ states.switch.wasmachine.name}} Today's Consumption"
        value_template: '{{ states.switch.wasmachine.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      wasmachine_verbruik:
        friendly_name: "Wasmachine verbruik"
        value_template: '{{ (float(states("input_number.wasmachine_stop")) - float(states("input_number.wasmachine_start"))) | round(3) }}'
        unit_of_measurement: 'kWh'
      wasmachine_status_time:
        friendly_name: "Wasmachine draaitijd"
        unit_of_measurement: 'minuten'
        value_template: >-
          {% if is_state('input_boolean.wasmachine', 'on') %}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
        entity_id: sensor.time
      wasmachine_status_value:
        friendly_name: "Wasmachine status"
        value_template: >-
          {% if is_state('input_boolean.wasmachine', 'on') %} Aan
          {% else %} Uit
          {% endif %}

# DROGER
  - platform: template
    sensors:
      droger_amps:
        friendly_name_template: "{{ states.switch.droger.name}} Current"
        value_template: '{{ states.switch.droger.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      droger_watts:
        friendly_name_template: "{{ states.switch.droger.name}} Current Consumption"
        value_template: '{{ states.switch.droger.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      droger_total_kwh:
        friendly_name_template: "{{ states.switch.droger.name}} Total Consumption"
        value_template: '{{ states.switch.droger.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      droger_volts:
        friendly_name_template: "{{ states.switch.droger.name}} Voltage"
        value_template: '{{ states.switch.droger.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      droger_today_kwh:
        friendly_name_template: "{{ states.switch.droger.name}} Today's Consumption"
        value_template: '{{ states.switch.droger.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      droger_verbruik:
        friendly_name: "Droger verbruik"
        value_template: '{{ (float(states("input_number.droger_stop")) - float(states("input_number.droger_start"))) | round(3) }}'
        unit_of_measurement: 'kWh'
      droger_status_time:
        friendly_name: "Droger draaitijd"
        unit_of_measurement: 'minuten'
        value_template: >-
          {% if is_state('input_boolean.droger', 'on') %}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
        entity_id: sensor.time
      droger_status_value:
        friendly_name: "Droger status"
        value_template: >-
          {% if is_state('input_boolean.droger', 'on') %} Aan
          {% else %} Uit
          {% endif %}  

################################################
## Automation
################################################
automation:
  - id: '1577787317846'
    alias: Waskamer - Wasmachine/droger - Aan
    trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_watts
      above: 5
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.droger_watts
      above: 5
      for:
        minutes: 5
    condition:
      condition: or
      conditions:
      - condition: template
        value_template: >
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            {{ is_state('input_boolean.wasmachine', 'off') }}
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            {{ is_state('input_boolean.droger', 'off') }}
          {% endif %}
    action:
    - service: input_boolean.turn_on
      data_template:
        entity_id: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}input_boolean.wasmachine
          {% elif trigger.entity_id == 'sensor.droger_watts' %}input_boolean.droger
          {% endif %}
    - service: input_number.set_value
      data_template:
        entity_id: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}input_number.wasmachine_start
          {% elif trigger.entity_id == 'sensor.droger_watts' %}input_number.droger_start
          {% endif %}
        value: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            {{ states.sensor.wasmachine_today_kwh.state }}
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            {{ states.sensor.droger_today_kwh.state }}
          {% endif %}
    - service: notify.family
      data_template:
        title: "Waskamer:"
        message: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            Wasprogramma gestart.
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            Droger gestart.
          {% endif %}
  
  - id: '1577787317847'
    alias: Waskamer - Wasmachine/droger - Uit
    trigger:
    - platform: numeric_state
      entity_id: sensor.wasmachine_watts
      below: 5
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.droger_watts
      below: 5
      for:
        minutes: 5
    condition:
      condition: or
      conditions:
      - condition: template
        value_template: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            {{ is_state('input_boolean.wasmachine', 'on') }}
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            {{ is_state('input_boolean.droger', 'on') }}
          {% endif %}
    action:
    - service: input_number.set_value
      data_template:
        entity_id: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}input_number.wasmachine_stop
          {% elif trigger.entity_id == 'sensor.droger_watts' %}input_number.droger_stop
          {% endif %}
        value: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            {{ states.sensor.wasmachine_today_kwh.state }}
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            {{ states.sensor.droger_today_kwh.state }}
          {% endif %}
    - service: notify.family
      data_template:
        title: "Waskamer:"
        message: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
            Wasprogramma gereed. Doorlooptijd: {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }} minuten. Verbruik: {{ states('sensor.wasmachine_verbruik') }} kWh.
          {% elif trigger.entity_id == 'sensor.droger_watts' %}
            Droger gereed. Doorlooptijd: {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }} minuten. Verbruik: {{ states('sensor.droger_verbruik') }} kWh.
          {% endif %}
    - service: input_boolean.turn_off
      data_template:
        entity_id: >-
          {% if trigger.entity_id == 'sensor.wasmachine_watts' %}input_boolean.wasmachine
          {% elif trigger.entity_id == 'sensor.droger_watts' %}input_boolean.droger
          {% endif %}
