################################################
## Packages
################################################
homeassistant:
  customize:
    switch.wasmachine:
      friendly_name: Wasmachine
    switch.droger:
      friendly_name: Droger
    sensor.wasmachine_current_consumption:
      friendly_name: Huidig verbruik wasmachine
      icon: mdi:washing-machine
    sensor.droger_current_consumption:
      friendly_name: Huidig verbruik droger
      icon: mdi:tumble-dryer
    sensor.wasmachine_status_time:
      friendly_name: Wasmachine draaitijd
      icon: mdi:washing-machine
    sensor.wasmachine_status_value:
      friendly_name: Wasmachine status
      icon: mdi:washing-machine
    sensor.droger_status_time:
      friendly_name: Droger draaitijd
      icon: mdi:tumble-dryer
    sensor.droger_status_value:
      friendly_name: Droger status
      icon: mdi:tumble-dryer

################################################
## Inputs
################################################
input_boolean:
  wasmachine:
    name: Wasmachine status
    initial: off
    icon: mdi:washing-machine
  droger:
    name: Droger status
    initial: off
    icon: mdi:tumble-dryer

input_number:
  wasmachine_start:
    name: Wasmachine start
    min: 0
    max: 999999999
  wasmachine_stop:
    name: Wasmachine stop
    min: 0
    max: 999999999
  droger_start:
    name: Droger start
    min: 0
    max: 999999999
  droger_stop:
    name: Droger stop
    min: 0
    max: 999999999

################################################
## Sensor
################################################
sensor:
  # WASMACHINE
  - platform: template
    sensors:
      wasmachine_verbruik:
        friendly_name: "Wasmachine verbruik"
        value_template: '{{ (float(states("input_number.wasmachine_stop")) - float(states("input_number.wasmachine_start"))) | round(3) }}'
        unit_of_measurement: "kWh"
      wasmachine_status_time:
        friendly_name: "Wasmachine draaitijd"
        unit_of_measurement: "minuten"
        value_template: >-
          {% if is_state('input_boolean.wasmachine', 'on') %}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
      wasmachine_status_value:
        friendly_name: "Wasmachine status"
        value_template: >-
          {% if is_state('input_boolean.wasmachine', 'on') %} Aan
          {% else %} Uit
          {% endif %}

  # DROGER
  - platform: template
    sensors:
      droger_verbruik:
        friendly_name: "Droger verbruik"
        value_template: '{{ (float(states("input_number.droger_stop")) - float(states("input_number.droger_start"))) | round(3) }}'
        unit_of_measurement: "kWh"
      droger_status_time:
        friendly_name: "Droger draaitijd"
        unit_of_measurement: "minuten"
        value_template: >-
          {% if is_state('input_boolean.droger', 'on') %}
            {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }}
          {% else %}
            0
          {% endif %}
      droger_status_value:
        friendly_name: "Droger status"
        value_template: >-
          {% if is_state('input_boolean.droger', 'on') %} Aan
          {% else %} Uit
          {% endif %}

################################################
## Automation
################################################
automation:
  - id: "1577787317846"
    alias: Waskamer - Wasmachine/droger - Aan
    trigger:
      - platform: numeric_state
        entity_id: sensor.wasmachine_current_consumption
        above: 5
        for:
          minutes: 5
      - platform: numeric_state
        entity_id: sensor.droger_current_consumption
        above: 5
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: >
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              {{ is_state('input_boolean.wasmachine', 'off') }}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              {{ is_state('input_boolean.droger', 'off') }}
            {% endif %}
    action:
      - service: input_boolean.turn_on
        data_template:
          entity_id: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}input_boolean.wasmachine
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}input_boolean.droger
            {% endif %}
      - service: input_number.set_value
        data_template:
          entity_id: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}input_number.wasmachine_start
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}input_number.droger_start
            {% endif %}
          value: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              {{ states.sensor.wasmachine_today_s_consumption.state }}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              {{ states.sensor.droger_today_s_consumption.state }}
            {% endif %}
      - service: notify.family
        data_template:
          title: "Waskamer:"
          message: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              Wasprogramma gestart - Tijdstip: {{now().strftime("%H:%M")}}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              Droger gestart - Tijdstip: {{now().strftime("%H:%M")}}
            {% endif %}
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.unnamed_room
  #         volume_level: 0.3
  #     - service: tts.google_say
  #       entity_id: media_player.unnamed_room
  #       data_template:
  #         message: >-
  #           {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
  #             Het wasprogramma is gestart.
  #           {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
  #             De droger is gestart.
  #           {% endif %}

  - id: "1577787317847"
    alias: Waskamer - Wasmachine/droger - Uit
    trigger:
      - platform: numeric_state
        entity_id: sensor.wasmachine_current_consumption
        below: 5
        for:
          minutes: 5
      - platform: numeric_state
        entity_id: sensor.droger_current_consumption
        below: 5
        for:
          minutes: 5
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              {{ is_state('input_boolean.wasmachine', 'on') }}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              {{ is_state('input_boolean.droger', 'on') }}
            {% endif %}
    action:
      - service: input_number.set_value
        data_template:
          entity_id: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}input_number.wasmachine_stop
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}input_number.droger_stop
            {% endif %}
          value: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              {{ states.sensor.wasmachine_today_s_consumption.state }}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              {{ states.sensor.droger_today_s_consumption.state }}
            {% endif %}
      - service: notify.family
        data_template:
          title: "Waskamer:"
          message: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
              Wasprogramma gereed - Tijdstip: {{now().strftime("%H:%M")}}
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
              Droger gereed - Tijdstip: {{now().strftime("%H:%M")}}
            {% endif %}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}input_boolean.wasmachine
            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}input_boolean.droger
            {% endif %}
  #      - service: media_player.volume_set
  #        data_template:
  #          entity_id: media_player.unnamed_room
  #          volume_level: 0.3
  #      - service: tts.google_say
  #        entity_id: media_player.unnamed_room
  #        data_template:
  #          message: >-
  #            {% if trigger.entity_id == 'sensor.wasmachine_current_consumption' %}
  #              Het wasprogramma is gereed. De doorlooptijd is {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }} minuten.
  #            {% elif trigger.entity_id == 'sensor.droger_current_consumption' %}
  #              De droger is gereed. De doorlooptijd is {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }} minuten.
  #            {% endif %}

  - id: "1577787317848"
    alias: "Sensor update Wasmachine/Droger draaitijd"
    trigger:
      - platform: time_pattern
        minutes: "/1"
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.wasmachine_status_time
      - service: homeassistant.update_entity
        entity_id: sensor.droger_status_time
