################################################
## Packages / Power Plugs
################################################
homeassistant:
# customize:
#   switch.wasmachine:
#     friendly_name: Wasmachine

################################################
## REST
################################################
rest_command:
  ventilation_set_speed:
    url: http://{{ host }}/api/v2/fan/setspeed.json?speed={{ speed }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_set_speed_timer:
    url: http://{{ host }}/api/v2/fan/setspeed.json?speed={{ speed }}&timer={{ timer }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_set_voltage:
    url: http://{{ host }}/api/v2/fan/setvoltage.json?voltage={{ voltage }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_reboot:
    url: http://{{ host }}/api/v1/systemconfig.json?reset=true
    username: !secret nrf905_username
    password: !secret nrf905_password

################################################
## FAN
################################################
fan:
  - platform: template
    fans:
      mechanische_ventilatie:
        friendly_name: Mechanische ventilatie
        value_template: >
          {{ states('sensor.mechanische_ventilatie_status') }}
        speed_template: >
          {{ state_attr('sensor.mechanische_ventilatie_status', 'speed') }}
        turn_on:
          service: script.ventilation_turn_on_off_dummy
        turn_off:
          service: script.ventilation_turn_on_off_dummy
        set_speed:
          service: script.ventilation_set_speed
          data:
            speed: "{{ speed }}"
        speeds:
          - low
          - medium
          - high
          - max

################################################
## Sensor
################################################
# sensor:
#   - platform: rest
#     name: Mechanische ventilatie status
#     scan_interval: 300
#     resource: !secret nrf905_status_url
#     username: !secret nrf905_username
#     password: !secret nrf905_password
#     value_template: >
#       {% if value_json['result'] == 'ok' %}
#         on
#       {% else %}
#         off
#       {% endif %}
#     json_attributes_path: "$.devices.*" # This might be different for each fan.
#     json_attributes:
#       - voltage
#       - percentage
#       - speed
#       - timer

input_text:
  ventilatie_status_low:
    name: Ventilatie Low
    initial: " "
  ventilatie_status_medium:
    name: Ventilatie Medium
    initial: " "
  ventilatie_status_high:
    name: Ventilatie High
    initial: " "
  ventilatie_status_max:
    name: Ventilatie Max
    initial: " "

sensor:
  - platform: template
    sensors:
      ventilatie_status_low:
        friendly_name: Ventilatie Low
        value_template: >
          {{ states('input_text.ventilatie_status_low') }}
      ventilatie_status_medium:
        friendly_name: Ventilatie Medium
        value_template: >
          {{ states('input_text.ventilatie_status_medium') }}
      ventilatie_status_high:
        friendly_name: Ventilatie High
        value_template: >
          {{ states('input_text.ventilatie_status_high') }}
      ventilatie_status_max:
        friendly_name: Ventilatie Max
        value_template: >
          {{ states('input_text.ventilatie_status_max') }}

################################################
## Script
################################################
script:
  ventilation_turn_on_off_dummy:
    mode: single
    sequence:
      - delay: 1
  ventilation_set_speed:
    mode: single
    fields:
      host:
        description: Hostname or ip
      speed:
        description: Set the fan speed (low/medium/high/max)
    sequence:
      - service: rest_command.ventilation_set_speed
        data:
          host: !secret nrf905_host
          speed: "{{ speed }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status
  ventilation_set_speed_timer:
    mode: single
    fields:
      host:
        description: Hostname or ip
      speed:
        description: Set the fan speed (low/medium/high/max)
      timer:
        description: Set the fan timer (number of minutes)
    sequence:
      - service: rest_command.ventilation_set_speed_timer
        data:
          host: !secret nrf905_host
          speed: "{{ speed }}"
          timer: "{{ timer }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status
  ventilation_set_voltage:
    mode: single
    fields:
      host:
        description: Hostname or ip
      voltage:
        description: Set the fan voltage, between 0.0 and 10.0
    sequence:
      - service: rest_command.ventilation_set_voltage
        data:
          host: !secret nrf905_host
          voltage: "{{ voltage }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status

  ventilation_reboot:
    mode: single
    fields:
      host:
        description: Hostname or ip
    sequence:
      - service: rest_command.ventilation_reboot
        data:
          host: !secret nrf905_host
      - delay: 5
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status
################################################
## Automation
################################################
# automation:
#   - alias: Ventilatie - Herstart ESP
#     trigger:
#       platform: time_pattern
#       minutes: "/10"
#     action:
#       service: script.turn_on
#       entity_id: script.ventilation_reboot

# LOVELACE
# type: entities
# show_header_toggle: false
# entities:
#   - entity: switch.mechanische_ventilatie
#   - type: 'custom:multiple-entity-row'
#     entity: sensor.mechanische_ventilatie_status
#     attribute: speed
#     name: Stand
#     icon: 'mdi:speedometer'
#     entities:
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:fan-speed-1'
#         name: Laag
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed
#           service_data:
#             speed: low
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:fan-speed-2'
#         name: Medium
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed
#           service_data:
#             speed: medium
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:fan-speed-3'
#         name: Hoog
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed
#           service_data:
#             speed: high
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:fan-plus'
#         name: Max
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed
#           service_data:
#             speed: max
#   - type: 'custom:multiple-entity-row'
#     entity: sensor.mechanische_ventilatie_status
#     attribute: timer
#     name: Timer
#     icon: 'mdi:timer'
#     entities:
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:clock-time-two-outline'
#         name: 10m
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed_timer
#           service_data:
#             speed: high
#             timer: 10
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:clock-time-six-outline'
#         name: 30m
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed_timer
#           service_data:
#             speed: high
#             timer: 30
#       - entity: sensor.mechanische_ventilatie_status
#         icon: 'mdi:clock-time-twelve-outline'
#         name: 60m
#         tap_action:
#           action: call-service
#           service: script.ventilation_set_speed_timer
#           service_data:
#             speed: high
#             timer: 60
#   - type: attribute
#     entity: sensor.mechanische_ventilatie_status
#     attribute: percentage
#     name: Percentage
#     icon: 'mdi:percent-outline'
#     suffix: '%'
#   - type: attribute
#     entity: sensor.mechanische_ventilatie_status
#     attribute: voltage
#     name: Voltage
#     icon: 'mdi:flash'
#     suffix: v
