################################################
## Packages / Power Plugs
################################################
homeassistant:
# customize:
#   switch.wasmachine:
#     friendly_name: Wasmachine

################################################
## REST
################################################
rest_command:
  ventilation_set_speed:
    url: http://{{ host }}/api/v2/fan/setspeed.json?speed={{ speed }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_set_speed_timer:
    url: http://{{ host }}/api/v2/fan/setspeed.json?speed={{ speed }}&timer={{ timer }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_set_voltage:
    url: http://{{ host }}/api/v2/fan/setvoltage.json?voltage={{ voltage }}
    username: !secret nrf905_username
    password: !secret nrf905_password
  ventilation_reboot:
    url: http://{{ host }}/api/v1/systemconfig.json?reset=true
    username: !secret nrf905_username
    password: !secret nrf905_password

################################################
## FAN
################################################
fan:
  - platform: template
    fans:
      mechanische_ventilatie:
        friendly_name: Mechanische ventilatie
        value_template: >
          {{ states('sensor.mechanische_ventilatie_status') }}
        speed_template: >
          {{ state_attr('sensor.mechanische_ventilatie_status', 'speed') }}
        turn_on:
          service: script.ventilation_turn_on_off_dummy
        turn_off:
          service: script.ventilation_turn_on_off_dummy
        set_speed:
          service: script.ventilation_set_speed
          data:
            speed: "{{ speed }}"
        speeds:
          - low
          - medium
          - high
          - max

################################################
## Sensor
################################################
sensor:
  - platform: rest
    name: Mechanische ventilatie status
    scan_interval: 120
    resource: !secret nrf905_status_url
    username: !secret nrf905_username
    password: !secret nrf905_password
    value_template: >
      {% if value_json['result'] == 'ok' %}
        on
      {% else %}
        off
      {% endif %}
    json_attributes_path: "$.devices.*" # This might be different for each fan.
    json_attributes:
      - voltage
      - percentage
      - speed
      - timer

################################################
## Script
################################################
script:
  ventilation_turn_on_off_dummy:
    mode: single
    sequence:
      - delay: 1
  ventilation_set_speed:
    mode: single
    fields:
      host:
        description: Hostname or ip
      speed:
        description: Set the fan speed (low/medium/high/max)
    sequence:
      - service: rest_command.ventilation_set_speed
        data:
          host: !secret nrf905_host
          speed: "{{ speed }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status
  ventilation_set_speed_timer:
    mode: single
    fields:
      host:
        description: Hostname or ip
      speed:
        description: Set the fan speed (low/medium/high/max)
      timer:
        description: Set the fan timer (number of minutes)
    sequence:
      - service: rest_command.ventilation_set_speed_timer
        data:
          host: !secret nrf905_host
          speed: "{{ speed }}"
          timer: "{{ timer }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status
  ventilation_set_voltage:
    mode: single
    fields:
      host:
        description: Hostname or ip
      voltage:
        description: Set the fan voltage, between 0.0 and 10.0
    sequence:
      - service: rest_command.ventilation_set_voltage
        data:
          host: !secret nrf905_host
          voltage: "{{ voltage }}"
      - delay: 1
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status

  ventilation_reboot:
    mode: single
    fields:
      host:
        description: Hostname or ip
    sequence:
      - service: rest_command.ventilation_reboot
        data:
          host: !secret nrf905_host
      - delay: 5
      - service: homeassistant.update_entity
        data:
          entity_id: sensor.mechanische_ventilatie_status

################################################
## Automation
################################################
automation:
  - alias: ventilatie - Herstart ESP
    trigger:
      platform: time_pattern
      hours: "/1"
    action:
      service: script.turn_on
      entity_id: script.ventilation_reboot
