################################################
## Packages / Waste
################################################
homeassistant:
  customize:
    sensor.afvalwijzer_today:
      friendly_name: Vandaag
    sensor.afvalwijzer_tomorrow:
      friendly_name: Morgen
    sensor.afvalwijzer_next_item:
      friendly_name: Next pickup item
    sensor.afvalwijzer_next_in_days:
      friendly_name: Next pickup in days
    input_boolean.waste_reminder:
      icon: mdi:reminder

    sensor.afvalwijzer_gft:
      friendly_name: GFT
      entity_picture: /local/afvalwijzer/GFT.png
    sensor.afvalwijzer_papier:
      friendly_name: Papier
      entity_picture: /local/afvalwijzer/Papier.png
    sensor.afvalwijzer_pmd:
      friendly_name: PMD
      entity_picture: /local/afvalwijzer/PMD.png
    sensor.afvalwijzer_restafval:
      friendly_name: Restafval
      entity_picture: /local/afvalwijzer/Restafval.png

################################################
## Inputs
################################################
input_boolean:
  waste_moved:
    name: Waste has been moved
    initial: "off"
    icon: mdi:delete-empty
  waste_reminder:
    name: Waste reminder enabled
    initial: "on"

################################################
## Sensor
################################################

sensor:
  # - platform: afvalwijzer
  #   provider: mijnafvalwijzer
  #   api_token: 5ef443e778f41c4f75c69459eea6e6ae0c2d92de729aa0fc61653815fbd6a8ca
  #   postal_code: !secret afvalwijzer_postcode
  #   street_number: !secret afvalwijzer_huisnummer
  #   default_label: 'Geen'

  - platform: afvalwijzer
    provider: mijnafvalwijzer
    postal_code: !secret afvalwijzer_postcode
    street_number: !secret afvalwijzer_huisnummer
  # exclude_list: ""

  # - platform: afvalwijzer
  #   provider: mijnafvalwijzer
  #   postal_code: 5384TC
  #   street_number: 5
  #   suffix: A
  #   id: test

  # default_label: 'Geen'
  - platform: template
    sensors:
      afvalwijzer_next_item_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_next_item', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_next_item', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_next_item', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_next_item', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Next pickup item"

      afvalwijzer_today_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_today', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_today', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_today', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_today', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Vandaag"

      afvalwijzer_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_tomorrow', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Morgen"

      afvalwijzer_day_after_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_day_after_tomorrow', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Overmorgen"

################################################
## Automation
################################################
automation:
  - alias: Afval - Herstel notificatie
    trigger:
      platform: state
      entity_id: input_boolean.waste_moved
      to: "on"
      for:
        hours: 12
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.waste_moved
      - service: input_boolean.turn_on
        entity_id: input_boolean.waste_reminder

  - alias: Afval - Bevestig notificatie
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_WASTE_MOVED
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.waste_moved

  - alias: Afval - Verzend notificatie - Tomorrow
    trigger:
      platform: time_pattern
      hours: "/1"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.waste_moved
          state: "off"
        - condition: state
          entity_id: input_boolean.waste_reminder
          state: "on"
        - condition: time
          after: "18:00:00"
          before: "23:00:00"
        - condition: template
          value_template: "{{ states('sensor.afvalwijzer_tomorrow_formatted') != 'Geen' }}"
    action:
      - service: notify.family
        data:
          title: "Afval"
          message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow_formatted.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
          data:
            push:
              badge: 0
              category: "afval"
  # - alias: Afval - Verzend notificatie - Today
  #   trigger:
  #     platform: time_pattern
  #     hours: "/1"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: input_boolean.waste_moved
  #         state: "off"
  #       - condition: state
  #         entity_id: input_boolean.waste_reminder
  #         state: "on"
  #       - condition: time
  #         after: "07:00:00"
  #         before: "09:00:00"
  #       - condition: template
  #         value_template: "{{ states('sensor.afvalwijzer_today_formatted') != 'Geen' }}"
  #       - condition: template
  #         value_template:
  #           "{{ (as_timestamp(now()) - as_timestamp(states.automation.kinderen_wakker_verzend_notificatie.attributes.last_triggered
  #           | default(0)) | int > 10800)}}"
  #   action:
  #     - service: notify.family
  #       data:
  #         title: "Afval"
  #         message: 'Het is vandaag - {{ now().strftime("%d-%m-%Y") }}. Afvaltype(n): {{ states.sensor.afvalwijzer_tomorrow_formatted.state }} wordt opgehaald op: {{ (as_timestamp(now()) + (24*3600)) | timestamp_custom("%d-%m-%Y", True) }}!'
  #         data:
  #           push:
  #             badge: 0
  #             category: "afval"
  #     - service: media_player.volume_set
  #       data_template:
  #         entity_id: media_player.unnamed_room
  #         volume_level: 0.3
  #     - service: tts.google_say
  #       entity_id: media_player.unnamed_room
  #       data_template:
  #         message: >-
  #           {% if trigger.entity_id == 'sensor.wasmachine_watts' %}
  #             Het wasprogramma is gereed. De doorlooptijd is {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.wasmachine.last_changed))/60) | round | int }} minuten.
  #           {% elif trigger.entity_id == 'sensor.droger_watts' %}
  #             De droger is gereed. De doorlooptijd is {{ ((as_timestamp(now())-as_timestamp(states.input_boolean.droger.last_changed))/60) | round | int }} minuten.
  #           {% endif %}
